export const tableContent = [
    {
        id: 0,
        attendeeName: "Emma Brown",
        eventName: "Indie Fest 2025",
        rating: 4,
        reviewText: "Superb music, amazing crowd!",
        date: "May 30, 2025",
        visibility: "Public",
    },
    {
        id: 1,
        attendeeName: "Liam Johnson",
        eventName: "Indie Fest 2025",
        rating: 5,
        reviewText: "Fantastic show, great energy!",
        date: "May 24, 2025",
        visibility: "Public",
    },
    {
        id: 2,
        attendeeName: "Noah Davis",
        eventName: "Indie Fest 2025",
        rating: 2,
        reviewText: "Unforgettable night, great fun!",
        date: "May 20, 2025",
        visibility: "Public",
    },
    {
        id: 3,
        attendeeName: "Sophia Rodriguez",
        eventName: "Indie Fest 2025",
        rating: 3,
        reviewText: "Awesome beats, fantastic time!",
        date: "May 17, 2025",
        visibility: "Public",
    },
    {
        id: 4,
        attendeeName: "Olivia Wilson",
        eventName: "Indie Fest 2025",
        rating: 4,
        reviewText: "Incredible show, loved it!",
        date: "May 14, 2025",
        visibility: "Public",
    },
    {
        id: 5,
        attendeeName: "Emma Brown",
        eventName: "Indie Fest 2025",
        rating: 4,
        reviewText: "Superb music, amazing crowd!",
        date: "May 12, 2025",
        visibility: "Public",
    },
    {
        id: 6,
        attendeeName: "Liam Johnson",
        eventName: "Indie Fest 2025",
        rating: 5,
        reviewText: "Fantastic show, great energy!",
        date: "May 10, 2025",
        visibility: "Public",
    },
    {
        id: 7,
        attendeeName: "Noah Davis",
        eventName: "Indie Fest 2025",
        rating: 2,
        reviewText: "Unforgettable night, great fun!",
        date: "May 7, 2025",
        visibility: "Public",
    },
    {
        id: 8,
        attendeeName: "Sophia Rodriguez",
        eventName: "Indie Fest 2025",
        rating: 3,
        reviewText: "Awesome beats, fantastic time!",
        date: "May 5, 2025",
        visibility: "Public",
    },
    {
        id: 9,
        attendeeName: "Olivia Wilson",
        eventName: "Indie Fest 2025",
        rating: 4,
        reviewText: "Incredible show, loved it!",
        date: "May 2, 2025",
        visibility: "Public",
    },
];
