export const tableContent = [
    {
        id: 0,
        categoryName: "Music",
        slug: "music",
        eventsCount: 45,
        status: "Active",
    },
    {
        id: 1,
        categoryName: "Business & Networking",
        slug: "business-networking",
        eventsCount: 92,
        status: "Active",
    },
    {
        id: 2,
        categoryName: "Sports & Fitness",
        slug: "sports-fitness",
        eventsCount: 27,
        status: "Active",
    },
    {
        id: 3,
        categoryName: "Arts & Culture",
        slug: "arts-culture",
        eventsCount: 61,
        status: "Active",
    },
    {
        id: 4,
        categoryName: "Technology",
        slug: "technology",
        eventsCount: 83,
        status: "Active",
    },
    {
        id: 5,
        categoryName: "Food & Drink",
        slug: "food-drink",
        eventsCount: 54,
        status: "Active",
    },
    {
        id: 6,
        categoryName: "Education & Workshops",
        slug: "education-workshops",
        eventsCount: 38,
        status: "Active",
    },
    {
        id: 7,
        categoryName: "Health & Wellness",
        slug: "health-wellness",
        eventsCount: 90,
        status: "Active",
    },
    {
        id: 8,
        categoryName: "Charity & Causes",
        slug: "charity-causes",
        eventsCount: 72,
        status: "Active",
    },
    {
        id: 9,
        categoryName: "Family & Kids",
        slug: "family-kids",
        eventsCount: 46,
        status: "Active",
    },
];
