export const tableContent = [
    {
        id: 0,
        ticketName: "VIP",
        price: "100",
        quantity: "200",
        sold: "180",
        salesStatus: "Active",
        visibility: "Public",
    },
    {
        id: 1,
        ticketName: "General",
        price: "50",
        quantity: "1,000",
        sold: "940",
        salesStatus: "Active",
        visibility: "Public",
    },
    {
        id: 2,
        ticketName: "Early Bird",
        price: "40",
        quantity: "300",
        sold: "300",
        salesStatus: "Sold Out",
        visibility: "Hidden",
    },
    {
        id: 3,
        ticketName: "VIP",
        price: "100",
        quantity: "200",
        sold: "180",
        salesStatus: "Sold Out",
        visibility: "Hidden",
    },
    {
        id: 4,
        ticketName: "General",
        price: "50",
        quantity: "1,000",
        sold: "940",
        salesStatus: "Active",
        visibility: "Public",
    },
    {
        id: 5,
        ticketName: "VIP",
        price: "100",
        quantity: "200",
        sold: "180",
        salesStatus: "Active",
        visibility: "Public",
    },
    {
        id: 6,
        ticketName: "General",
        price: "50",
        quantity: "1,000",
        sold: "940",
        salesStatus: "Active",
        visibility: "Public",
    },
    {
        id: 7,
        ticketName: "Early Bird",
        price: "40",
        quantity: "300",
        sold: "300",
        salesStatus: "Sold Out",
        visibility: "Hidden",
    },
    {
        id: 8,
        ticketName: "VIP",
        price: "100",
        quantity: "200",
        sold: "180",
        salesStatus: "Active",
        visibility: "Public",
    },
    {
        id: 9,
        ticketName: "General",
        price: "50",
        quantity: "1,000",
        sold: "940",
        salesStatus: "Sold Out",
        visibility: "Hidden",
    },
];
