export const tableContent = [
    {
        id: 0,
        eventName: "Cultural Fusion Fest 2025",
        dateAndTime: "Mar 15, 2024, 3 PM",
        status: "Published",
        ticketsSold: 456,
        revenue: "$1,597",
    },
    {
        id: 1,
        eventName: "Creative Convergence 2025",
        dateAndTime: "Oct 5, 2023, 11 AM",
        status: "Published",
        ticketsSold: 789,
        revenue: "$2,745",
    },
    {
        id: 2,
        eventName: "Imagination Expo 2025",
        dateAndTime: "Dec 1, 2024, 8 AM",
        status: "Cancelled",
        ticketsSold: 234,
        revenue: "$7,184",
    },
    {
        id: 3,
        eventName: "Visionary Vibes 2025",
        dateAndTime: "Apr 30, 2025, 2 PM",
        status: "Draft",
        ticketsSold: 876,
        revenue: "$4,823",
    },
    {
        id: 4,
        eventName: "Artistry Unleashed 2025",
        dateAndTime: "Sep 9, 2023, 4 PM",
        status: "Published",
        ticketsSold: 849,
        revenue: "$3,123",
    },
    {
        id: 5,
        eventName: "Cultural Fusion Fest 2025",
        dateAndTime: "Mar 15, 2024, 3 PM",
        status: "Published",
        ticketsSold: 456,
        revenue: "$1,597",
    },
    {
        id: 6,
        eventName: "Creative Convergence 2025",
        dateAndTime: "Oct 5, 2023, 11 AM",
        status: "Published",
        ticketsSold: 789,
        revenue: "$2,745",
    },
    {
        id: 7,
        eventName: "Imagination Expo 2025",
        dateAndTime: "Dec 1, 2024, 8 AM",
        status: "Cancelled",
        ticketsSold: 234,
        revenue: "$7,184",
    },
    {
        id: 8,
        eventName: "Visionary Vibes 2025",
        dateAndTime: "Apr 30, 2025, 2 PM",
        status: "Draft",
        ticketsSold: 876,
        revenue: "$4,823",
    },
    {
        id: 9,
        eventName: "Artistry Unleashed 2025",
        dateAndTime: "Sep 9, 2023, 4 PM",
        status: "Published",
        ticketsSold: 849,
        revenue: "$3,123",
    },
];
