export const tableContent = [
    {
        id: 0,
        eventName: "Imagination Expo 2025",
        ticketsSold: "582",
        revenue: "39,800",
        platformFee: "100",
        netEarnings: "39,700",
        status: "Paid",
    },
    {
        id: 1,
        eventName: "Dreamers' Festival 2025",
        ticketsSold: "804",
        revenue: "50,000",
        platformFee: "100",
        netEarnings: "49,900",
        status: "Paid",
    },
    {
        id: 2,
        eventName: "Creative Convergence 2025",
        ticketsSold: "148",
        revenue: "34,900",
        platformFee: "100",
        netEarnings: "34,800",
        status: "Available",
    },
    {
        id: 3,
        eventName: "Artistic Odyssey 2025",
        ticketsSold: "295",
        revenue: "63,120",
        platformFee: "100",
        netEarnings: "63,020",
        status: "Pending",
    },
    {
        id: 4,
        eventName: "Imagination Expo 2025",
        ticketsSold: "582",
        revenue: "39,800",
        platformFee: "100",
        netEarnings: "39,700",
        status: "Paid",
    },
    {
        id: 5,
        eventName: "Dreamers' Festival 2025",
        ticketsSold: "804",
        revenue: "50,000",
        platformFee: "100",
        netEarnings: "49,900",
        status: "Paid",
    },
    {
        id: 6,
        eventName: "Creative Convergence 2025",
        ticketsSold: "148",
        revenue: "34,900",
        platformFee: "100",
        netEarnings: "34,800",
        status: "Available",
    },
    {
        id: 7,
        eventName: "Artistic Odyssey 2025",
        ticketsSold: "295",
        revenue: "63,120",
        platformFee: "100",
        netEarnings: "63,020",
        status: "Pending",
    },
    {
        id: 8,
        eventName: "Imagination Expo 2025",
        ticketsSold: "582",
        revenue: "39,800",
        platformFee: "100",
        netEarnings: "39,700",
        status: "Paid",
    },
    {
        id: 9,
        eventName: "Dreamers' Festival 2025",
        ticketsSold: "804",
        revenue: "50,000",
        platformFee: "100",
        netEarnings: "49,900",
        status: "Paid",
    },
];
