export const tableContent = [
    {
        id: 0,
        organizer: "Olivia Smith",
        amount: "$2,745",
        requestedOn: "March 15, 2025",
        status: "Pending",
        processedOn: "-",
    },
    {
        id: 1,
        organizer: "Sophia Bennett",
        amount: "$8,361",
        requestedOn: "April 5, 2025",
        status: "Approved",
        processedOn: "May 15, 2025",
    },
    {
        id: 2,
        organizer: "Lucas Martinez",
        amount: "$4,029",
        requestedOn: "April 10, 2025",
        status: "Approved",
        processedOn: "May 27, 2025",
    },
    {
        id: 3,
        organizer: "Liam Johnson",
        amount: "$1,597",
        requestedOn: "April 15, 2025",
        status: "Pending",
        processedOn: "-",
    },
    {
        id: 4,
        organizer: "Emma Brown",
        amount: "$3,250",
        requestedOn: "April 20, 2025",
        status: "Rejected",
        processedOn: "-",
    },
    {
        id: 5,
        organizer: "Olivia Smith",
        amount: "$2,745",
        requestedOn: "May 15, 2025",
        status: "Pending",
        processedOn: "-",
    },
    {
        id: 6,
        organizer: "Sophia Bennett",
        amount: "$8,361",
        requestedOn: "June 5, 2025",
        status: "Approved",
        processedOn: "June 10, 2025",
    },
    {
        id: 7,
        organizer: "Lucas Martinez",
        amount: "$4,029",
        requestedOn: "June 10, 2025",
        status: "Approved",
        processedOn: "June 23, 2025",
    },
    {
        id: 8,
        organizer: "Liam Johnson",
        amount: "$1,597",
        requestedOn: "June 15, 2025",
        status: "Pending",
        processedOn: "-",
    },
    {
        id: 9,
        organizer: "Emma Brown",
        amount: "$3,250",
        requestedOn: "June 20, 2025",
        status: "Rejected",
        processedOn: "-",
    },
];
