export const tableContent = [
    {
        id: 0,
        code: "EARLYBIRD",
        discount: "20% OFF",
        used: "Unlimited",
        expiryDate: "May 15, 2025",
        status: "Active",
    },
    {
        id: 1,
        code: "EARLYBIRD",
        discount: "10% OFF",
        used: "Unlimited",
        expiryDate: "Jun 15, 2025",
        status: "Active",
    },
    {
        id: 2,
        code: "EARLYBIRD",
        discount: "15% OFF",
        used: "Unlimited",
        expiryDate: "Sep 15, 2025",
        status: "Active",
    },
    {
        id: 3,
        code: "EARLYBIRD",
        discount: "5% OFF",
        used: "Unlimited",
        expiryDate: "Oct 15, 2025",
        status: "Active",
    },
    {
        id: 4,
        code: "EARLYBIRD",
        discount: "14% OFF",
        used: "Unlimited",
        expiryDate: "Dec 15, 2025",
        status: "Active",
    },
    {
        id: 5,
        code: "EARLYBIRD",
        discount: "20% OFF",
        used: "Unlimited",
        expiryDate: "May 15, 2024",
        status: "Active",
    },
    {
        id: 6,
        code: "EARLYBIRD",
        discount: "10% OFF",
        used: "Unlimited",
        expiryDate: "Jun 15, 2024",
        status: "Active",
    },
    {
        id: 7,
        code: "EARLYBIRD",
        discount: "15% OFF",
        used: "Unlimited",
        expiryDate: "Sep 15, 2024",
        status: "Active",
    },
    {
        id: 8,
        code: "EARLYBIRD",
        discount: "5% OFF",
        used: "Unlimited",
        expiryDate: "Oct 15, 2024",
        status: "Active",
    },
    {
        id: 9,
        code: "EARLYBIRD",
        discount: "14% OFF",
        used: "Unlimited",
        expiryDate: "Dec 15, 2024",
        status: "Active",
    },
];
