export const tableContent = [
    {
        id: 0,
        name: "Liam Smith",
        email: "liamsmith@gmail.com",
        ticketType: "VIP",
        purchaseDate: "June 15, 2025",
        checkInStatus: "Paid",
    },
    {
        id: 1,
        name: "Sophia Johnson",
        email: "sophiajohnson@gmail.com",
        ticketType: "General",
        purchaseDate: "May 30, 2025",
        checkInStatus: "Cancelled",
    },
    {
        id: 2,
        name: "Olivia Brown",
        email: "Olivia Brown",
        ticketType: "VIP",
        purchaseDate: "July 4, 2025",
        checkInStatus: "Checked In",
    },
    {
        id: 3,
        name: "Noah Davis",
        email: "noahaavis@gmail.com",
        ticketType: "General",
        purchaseDate: "May 1, 2025",
        checkInStatus: "Not Checked In",
    },
    {
        id: 4,
        name: "Mia Thomas",
        email: "miathomas@gmail.com",
        ticketType: "VIP",
        purchaseDate: "May 18, 2025",
        checkInStatus: "Paid",
    },
    {
        id: 5,
        name: "Liam Smith",
        email: "liamsmith@gmail.com",
        ticketType: "VIP",
        purchaseDate: "June 15, 2025",
        checkInStatus: "Paid",
    },
    {
        id: 6,
        name: "Sophia Johnson",
        email: "sophiajohnson@gmail.com",
        ticketType: "General",
        purchaseDate: "May 30, 2025",
        checkInStatus: "Cancelled",
    },
    {
        id: 7,
        name: "Olivia Brown",
        email: "Olivia Brown",
        ticketType: "VIP",
        purchaseDate: "July 4, 2025",
        checkInStatus: "Checked In",
    },
    {
        id: 8,
        name: "Noah Davis",
        email: "noahaavis@gmail.com",
        ticketType: "General",
        purchaseDate: "May 1, 2025",
        checkInStatus: "Checked In",
    },
    {
        id: 9,
        name: "Mia Thomas",
        email: "miathomas@gmail.com",
        ticketType: "VIP",
        purchaseDate: "May 18, 2025",
        checkInStatus: "Paid",
    },
];
